fastq:
    folder: /entrepot/donnees/seaconnect/gbs_mullus/cleaned
    file:
        - C6JATANXX_5
        - C6JATANXX_6
        - C8BJGANXX_1
        - C6JATANXX_4
        - C6JATANXX_3
        - C6JATANXX_2
container:
    seaconnect.simg
process_radtags:
    barcodesFolder: 01-infos/barcodes
    inTypeFile: gzfastq
    barcodesDist: 1
    encoded: phred33
    qualScore: 0
    enzymes : 
        - pstI
        - bfaI
